### ISSUE TITLE
Input sanitization

### ISSUE THREAD

**Issue by grantdobbe** [NuCivic/nucivic_connector#1]
Function nucivic_connector_add_recipients() on line 23 assumes that the contents of update_notify_emails is friendly. That input should be sanitized before being sent via XML-RPC.

See https://api.drupal.org/api/drupal/includes!common.inc/group/sanitization/7

I'd suggest check_markup or check_plain.

**Comment by sheldonrampton** [comment]
Assigning this to Grant for review and closing if completed.
